server.port=9090

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#Employee Route

spring.cloud.gateway.server.webflux.routes[0].id=employee-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/employees/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=AddRequestHeader=X-App,API-Gateway
spring.cloud.gateway.server.webflux.routes[0].filters[1]=AddResponseHeader=X-Version,v1.0
# spring.cloud.gateway.server.webflux.routes[0].filters[2]=StripPrefix=1

#Department Route

spring.cloud.gateway.server.webflux.routes[1].id=department-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/departments/**

api.security.token=Arjun123

spring.boot.admin.client.url=http://localhost:9091

management.endpoints.web.exposure.include=*

message=Hello from api-gateway config server!